```{r knitr, echo = FALSE, results = 'hide', warning = FALSE}
library(knitr)
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE, 
  message = FALSE,
  fig.align = 'center'
)
suppressPackageStartupMessages(
  suppressWarnings(
    library(ggplot2)
  )
)
suppressPackageStartupMessages(
  suppressWarnings(
    library(INBOtheme)
  )
)
if (interactive()) {
  theme_set(
    theme_inbo(base_family = "FlandersArtSans-Regular", base_size = 10)
  )
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(
        theme_inbo(base_family = "FlandersArtSans-Regular", base_size = 12)
      )
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(
        theme_inbo(base_family = "FlandersArtSans-Regular", base_size = 9)
      )
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(
        theme_inbo(base_family = "FlandersArtSans-Regular", base_size = 12)
      )
    }
  )
}

gewestNames <- sapply(input$species_gewest, function(x)
    translate(id = x)$title) 
    
reportNames <- names(dashReport)[!sapply(reactiveValuesToList(dashReport), is.null)]    
```

---
subtitle: "`r toString(gewestNames)`"
---


```{r intro, results = "asis"}
cat("*",  translate(id = 'species')$title, ":", taxonName(), "\n")
cat("*",  translate(id = 'region')$title, ":", toString(gewestNames), "\n")
```


```{r sectionObservations, results = "asis"}
myTitle <- translate("observations")$title
cat("#", toupper(myTitle), "\n") 
incProgress(amount = 0.2, detail = myTitle)

childOutput <- lapply(grep("observations", reportNames, value = TRUE), function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


```{r sectionIndicators, results = "asis"}
myTitle <- translate("indicators")$title
cat("#", toupper(myTitle), "\n") 
incProgress(amount = 0.2, detail = myTitle)

childOutput <- lapply(grep("indicators", reportNames, value = TRUE), function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


```{r sectionReporting, results = "asis"}
myTitle <- translate("reporting")$title
cat("#", toupper(myTitle), "\n") 
incProgress(amount = 0.2, detail = myTitle)

childOutput <- lapply(grep("reporting", reportNames, value = TRUE), function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


```{r sectionManagement, results = "asis"}
myTitle <- translate("management")$title
cat("#", toupper(myTitle), "\n") 
incProgress(amount = 0.2, detail = myTitle)

mgtKey <- if (taxonName() %in% cubeSpecies)
    "management" else if (taxonName() %in% heatSpecies)
    "management2" else
    "management3"
# Define order to be the same as in the app    
managementIds <- paste0(mgtKey, c("_active-mapHeat", "_observed-mapHeat", 
"-mapOccurrence", "_lente-barplotLenteNesten", "_province-countNesten", "_provinceTable-tableNesten", 
"-countYearGroup"))
managementIds <- managementIds[managementIds %in% reportNames]

childOutput <- lapply(managementIds, function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
```
