---
title: "`r paste0(translate(id = 'species_information')$title, ': ', taxonName())`" 
author: "`r paste0('v', packageVersion('alienSpecies'))`"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
toc-title: "r paste(translate(id = 'contents')$title"
output: 
   oaStyle::pdf_report:
      logo: NULL
      bigLogoSize: 15cm
      always_allow_html: yes
      latex_engine: pdflatex
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
editor_options: 
  chunk_output_type: console
---

```{r knitr, echo = FALSE, results = 'hide', warning = FALSE}
library(knitr)
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE, 
  message = FALSE,
  fig.align = 'center',
  fig.width = 10, 
  fig.height = 8
)

gewestNames <- sapply(input$species_gewest, function(x)
    translate(id = x)$title) 
    
reportNames <- names(dashReport)[!sapply(reactiveValuesToList(dashReport), is.null)]    
```

---
subtitle: "`r toString(gewestNames)`"
---


```{r intro, results = "asis"}
cat("*",  translate(id = 'species')$title, ":", taxonName(), "\n")
cat("*",  translate(id = 'region')$title, ":", toString(gewestNames), "\n")
```



```{r sectionObservations, results = "asis"}
myTitle <- translate("observations")$title
cat("#", toupper(myTitle), "\n\n") 
incProgress(amount = 0.2, detail = myTitle)

childOutput <- lapply(grep("observations", reportNames, value = TRUE), function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


```{r sectionIndicators, results = "asis"}
myTitle <- translate("indicators")$title
cat("#", toupper(myTitle), "\n\n") 
incProgress(amount = 0.2, detail = myTitle)

childOutput <- lapply(grep("indicators", reportNames, value = TRUE), function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


```{r sectionReporting, results = "asis"}
myTitle <- translate("reporting")$title
cat("#", toupper(myTitle), "\n\n") 
incProgress(amount = 0.2, detail = myTitle)

childOutput <- lapply(grep("reporting", reportNames, value = TRUE), function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


```{r sectionManagement, results = "asis"}
myTitle <- translate("management")$title
cat("#", toupper(myTitle), "\n\n") 
incProgress(amount = 0.2, detail = myTitle)

mgtKey <- if (taxonName() %in% cubeSpecies)
    "management" else if (taxonName() %in% heatSpecies)
    "management2" else
    "management3"
# Define order to be the same as in the app    
managementIds <- paste0(mgtKey, c("_active-mapHeat", "_observed-mapHeat", 
"-mapOccurrence", "_lente-barplotLenteNesten", "_province-countNesten", "_provinceTable-tableNesten", 
"-countYearGroup"))
managementIds <- managementIds[managementIds %in% reportNames]

childOutput <- lapply(managementIds, function(id) 
  knitr::knit_child("plotSpecies.Rmd", quiet = TRUE, envir = environment())
)
if (length(childOutput) == 0)
  cat(translate("noData")$title) else
  cat(unlist(childOutput), sep = '\n')
``` 


