default:
  bucket: inbo-exotenportaal-uat-eu-west-1-default
  credentials:
    region: Sys.getenv('AWS_DEFAULT_REGION', unset = 'eu-west-1')
    id: Sys.getenv('AWS_ACCESS_KEY_ID')
    secret: Sys.getenv('AWS_SECRET_ACCESS_KEY')
  datacheck: false
  defaultYear: 2022


